# Generated by Django 6.0.7 on 2026-08-08 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='ac_type',
            field=models.CharField(blank=True, choices=[('B737', 'Boeing 737'), ('B777', 'Boeing 777'), ('A32X', 'Airbus 32X'), ('A33X', 'Airbus 33X'), ('MULTY', 'MULTY TYPE')], max_length=10),
        ),
        migrations.AddField(
            model_name='customuser',
            name='middle_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='position',
            field=models.CharField(blank=True, choices=[('КВС', 'Командир ВС'), ('ВП', 'Второй пилот'), ('ПИ', 'Пилот-инструктор')], max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='GroupsDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200, verbose_name='Описание группы')),
                ('is_fixed', models.BooleanField(default=False, help_text='Фиксированные группы нельзя удалить', verbose_name='Фиксированная группа')),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='description', to='auth.group')),
            ],
        ),
    ]
