# Generated by Django 6.0.7 on 2026-08-09 14:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0008_alter_question_ac_type_alter_questiondraft_ac_type_and_more'),
        ('users', '0002_customuser_ac_type_customuser_middle_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_users', to='questions.themes', verbose_name='Тема')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_themes', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Тема пользователя',
                'verbose_name_plural': 'Темы пользователей',
                'unique_together': {('user', 'theme')},
            },
        ),
    ]
