# Generated by Django 6.0.7 on 2026-08-16 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_usertheme'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': [('can_deactivate_user', 'Can deactivate any user')]},
        ),
        migrations.AlterModelOptions(
            name='usertheme',
            options={'permissions': [('can_change_user_themes', 'Can add or remove user Themes')], 'verbose_name': 'Тема пользователя', 'verbose_name_plural': 'Темы пользователей'},
        ),
    ]
