# Generated by Django 6.0.7 on 2026-07-24 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Themes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название Темы')),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Тема',
                'verbose_name_plural': 'Темы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='Текст вопроса')),
                ('ac_type', models.CharField(choices=[('B737', 'Boeing 737'), ('B777', 'Boeing 777'), ('A32X', 'Airbus 32X'), ('A33X', 'Airbus 33X'), ('ANY', 'ANY TYPE')], max_length=10, verbose_name='Тип ВС')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опубликован')),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('q_kind', models.BooleanField(default=False, verbose_name='Один или Несколько правильных ответов')),
                ('q_weight', models.FloatField(default=1.0, verbose_name='Вес вопроса')),
                ('is_time_limited', models.BooleanField(default=False, verbose_name='С ограничением по времени')),
                ('question_img', models.ImageField(blank=True, null=True, upload_to='questions/img/', verbose_name='Картинка к вопросу')),
                ('comment_img', models.ImageField(blank=True, null=True, upload_to='comments/', verbose_name='Картинка пояснения')),
                ('comment_text', models.TextField(blank=True, null=True, verbose_name='Текст пояснения')),
                ('is_draft', models.BooleanField(default=True, verbose_name='Черновик')),
                ('is_paraphrased', models.BooleanField(default=False, help_text='Перефразирован ли вопрос', verbose_name='Does the question paraphrased')),
                ('previous_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_versions', to='questions.question', verbose_name='Предыдущая версия')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='questions.themes', verbose_name='Тема')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
                'ordering': ['theme__name', 'question'],
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=200, verbose_name='Формулировка ответа')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Правильный Ответ на вопрос')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='questions.question')),
            ],
            options={
                'verbose_name': 'Ответ',
                'verbose_name_plural': 'Ответы',
                'ordering': ['question'],
            },
        ),
        migrations.CreateModel(
            name='QuestionSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='Текст вопроса')),
                ('ac_type', models.CharField(choices=[('B737', 'Boeing 737'), ('B777', 'Boeing 777'), ('A32X', 'Airbus 32X'), ('A33X', 'Airbus 33X'), ('ANY', 'ANY TYPE')], max_length=10, verbose_name='Тип ВС')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опубликован')),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('q_kind', models.BooleanField(default=False, verbose_name='Один или Несколько правильных ответов')),
                ('q_weight', models.FloatField(default=1.0, verbose_name='Вес вопроса')),
                ('is_time_limited', models.BooleanField(default=False, verbose_name='С ограничением по времени')),
                ('question_img', models.ImageField(blank=True, null=True, upload_to='questions/img/', verbose_name='Картинка к вопросу')),
                ('comment_img', models.ImageField(blank=True, null=True, upload_to='comments/', verbose_name='Картинка пояснения')),
                ('comment_text', models.TextField(blank=True, null=True, verbose_name='Текст пояснения')),
                ('original_question', models.ForeignKey(help_text='Это перефразированный вопрос', on_delete=django.db.models.deletion.CASCADE, to='questions.question', verbose_name='Original question')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='questions.themes', verbose_name='Тема')),
            ],
            options={
                'verbose_name': 'Перефразированный Вопрос',
                'verbose_name_plural': 'Перефразированные вопросы Вопросы',
                'ordering': ['theme__name', 'question'],
            },
        ),
    ]
