# Generated by Django 6.0.7 on 2026-07-29 06:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ['question', 'answer_order'], 'verbose_name': 'Ответ', 'verbose_name_plural': 'Ответы'},
        ),
        migrations.RemoveField(
            model_name='question',
            name='is_draft',
        ),
        migrations.RemoveField(
            model_name='question',
            name='is_paraphrased',
        ),
        migrations.AddField(
            model_name='question',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата создания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_questions', to=settings.AUTH_USER_MODEL, verbose_name='Создатель'),
        ),
        migrations.AddField(
            model_name='question',
            name='is_archived',
            field=models.BooleanField(default=False, help_text='Заменён на новую версию', verbose_name='Архивный'),
        ),
        migrations.AlterField(
            model_name='question',
            name='is_published',
            field=models.BooleanField(default=False, help_text='Доступен для тестов', verbose_name='Опубликован'),
        ),
        migrations.AlterField(
            model_name='question',
            name='previous_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_versions', to='questions.question', verbose_name='Предыдущая версия'),
        ),
        migrations.AlterField(
            model_name='question',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='question',
            name='q_kind',
            field=models.CharField(choices=[('SINGLE', 'Один ответ'), ('MULTY', 'Множественный ответ')], default='SINGLE', max_length=20, verbose_name='Один или Несколько правильных ответов'),
        ),
        migrations.CreateModel(
            name='QuestionDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='Текст вопроса')),
                ('ac_type', models.CharField(choices=[('B737', 'Boeing 737'), ('B777', 'Boeing 777'), ('A32X', 'Airbus 32X'), ('A33X', 'Airbus 33X'), ('ANY', 'ANY TYPE')], max_length=10, verbose_name='Тип ВС')),
                ('q_kind', models.CharField(choices=[('SINGLE', 'Один ответ'), ('MULTY', 'Множественный ответ')], default='SINGLE', max_length=20, verbose_name='Один или Несколько правильных ответов')),
                ('q_weight', models.FloatField(default=1.0, verbose_name='Вес вопроса')),
                ('is_time_limited', models.BooleanField(default=False, verbose_name='С ограничением по времени')),
                ('question_img', models.ImageField(blank=True, null=True, upload_to='questions/img/', verbose_name='Картинка к вопросу')),
                ('comment_img', models.ImageField(blank=True, null=True, upload_to='questions/comments/', verbose_name='Картинка пояснения')),
                ('comment_text', models.TextField(blank=True, null=True, verbose_name='Текст пояснения')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_drafts', to=settings.AUTH_USER_MODEL, verbose_name='Создатель черновика')),
                ('original_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drafts', to='questions.question', verbose_name='Оригинальный вопрос')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='questions.themes', verbose_name='Тема')),
            ],
            options={
                'verbose_name': 'Черновик вопроса',
                'verbose_name_plural': 'Черновики вопросов',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='answer',
            name='question_draft',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='questions.questiondraft'),
        ),
        migrations.CreateModel(
            name='QuestionParaphrase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='Текст вопроса')),
                ('ac_type', models.CharField(choices=[('B737', 'Boeing 737'), ('B777', 'Boeing 777'), ('A32X', 'Airbus 32X'), ('A33X', 'Airbus 33X'), ('ANY', 'ANY TYPE')], max_length=10, verbose_name='Тип ВС')),
                ('q_kind', models.CharField(choices=[('SINGLE', 'Один ответ'), ('MULTY', 'Множественный ответ')], default='SINGLE', max_length=20, verbose_name='Один или Несколько правильных ответов')),
                ('q_weight', models.FloatField(default=1.0, verbose_name='Вес вопроса')),
                ('is_time_limited', models.BooleanField(default=False, verbose_name='С ограничением по времени')),
                ('question_img', models.ImageField(blank=True, null=True, upload_to='questions/img/', verbose_name='Картинка к вопросу')),
                ('comment_img', models.ImageField(blank=True, null=True, upload_to='questions/comments/', verbose_name='Картинка пояснения')),
                ('comment_text', models.TextField(blank=True, null=True, verbose_name='Текст пояснения')),
                ('is_published', models.BooleanField(default=False, help_text='Доступен для использования в тестах', verbose_name='Опубликован')),
                ('usage_count', models.PositiveIntegerField(default=0, verbose_name='Количество использований')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_paraphrases', to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
                ('original_question', models.ForeignKey(help_text='Это перефразированный вопрос', on_delete=django.db.models.deletion.CASCADE, to='questions.question', verbose_name='Original question')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='questions.themes', verbose_name='Тема')),
            ],
            options={
                'verbose_name': 'Перефразированный вопрос',
                'verbose_name_plural': 'Перефразированные вопросы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='QuestionSnapshot',
        ),
        migrations.AddIndex(
            model_name='questiondraft',
            index=models.Index(fields=['original_question'], name='questions_q_origina_ac7f54_idx'),
        ),
        migrations.AddIndex(
            model_name='questiondraft',
            index=models.Index(fields=['created_by', 'updated_at'], name='questions_q_created_d1899f_idx'),
        ),
        migrations.AddIndex(
            model_name='questiondraft',
            index=models.Index(fields=['-created_at'], name='questions_q_created_c64858_idx'),
        ),
        migrations.AddIndex(
            model_name='questionparaphrase',
            index=models.Index(fields=['original_question', 'is_published'], name='questions_q_origina_d9eed5_idx'),
        ),
    ]
