# Generated by Django 6.0.7 on 2026-07-29 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_alter_answer_options_remove_question_is_draft_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionparaphrase',
            name='original_question',
            field=models.ForeignKey(help_text='Это перефразированный вопрос', on_delete=django.db.models.deletion.CASCADE, related_name='paraphrases', to='questions.question', verbose_name='Original question'),
        ),
    ]
