# Generated by Django 6.0.7 on 2026-08-04 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_alter_question_comment_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.themes', verbose_name='Тема'),
        ),
        migrations.AlterField(
            model_name='questiondraft',
            name='theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.themes', verbose_name='Тема'),
        ),
        migrations.AlterField(
            model_name='questionparaphrase',
            name='theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.themes', verbose_name='Тема'),
        ),
    ]
