# Generated by Django 6.0.7 on 2026-08-04 10:16

import core.field_validators.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_alter_question_theme_alter_questiondraft_theme_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='comment_img',
            field=models.ImageField(blank=True, null=True, upload_to='questions/comments/', validators=[core.field_validators.validators.validate_image], verbose_name='Картинка пояснения'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_img',
            field=models.ImageField(blank=True, null=True, upload_to='questions/img/', validators=[core.field_validators.validators.validate_image], verbose_name='Картинка к вопросу'),
        ),
        migrations.AlterField(
            model_name='questiondraft',
            name='comment_img',
            field=models.ImageField(blank=True, null=True, upload_to='questions/comments/', validators=[core.field_validators.validators.validate_image], verbose_name='Картинка пояснения'),
        ),
        migrations.AlterField(
            model_name='questiondraft',
            name='question_img',
            field=models.ImageField(blank=True, null=True, upload_to='questions/img/', validators=[core.field_validators.validators.validate_image], verbose_name='Картинка к вопросу'),
        ),
        migrations.AlterField(
            model_name='questionparaphrase',
            name='comment_img',
            field=models.ImageField(blank=True, null=True, upload_to='questions/comments/', validators=[core.field_validators.validators.validate_image], verbose_name='Картинка пояснения'),
        ),
        migrations.AlterField(
            model_name='questionparaphrase',
            name='question_img',
            field=models.ImageField(blank=True, null=True, upload_to='questions/img/', validators=[core.field_validators.validators.validate_image], verbose_name='Картинка к вопросу'),
        ),
    ]
