# Generated by Django 6.0.7 on 2026-08-08 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0007_alter_answer_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='ac_type',
            field=models.CharField(choices=[('B737', 'Boeing 737'), ('B777', 'Boeing 777'), ('A32X', 'Airbus 32X'), ('A33X', 'Airbus 33X'), ('MULTY', 'MULTY TYPE')], max_length=10, verbose_name='Тип ВС'),
        ),
        migrations.AlterField(
            model_name='questiondraft',
            name='ac_type',
            field=models.CharField(choices=[('B737', 'Boeing 737'), ('B777', 'Boeing 777'), ('A32X', 'Airbus 32X'), ('A33X', 'Airbus 33X'), ('MULTY', 'MULTY TYPE')], max_length=10, verbose_name='Тип ВС'),
        ),
        migrations.AlterField(
            model_name='questionparaphrase',
            name='ac_type',
            field=models.CharField(choices=[('B737', 'Boeing 737'), ('B777', 'Boeing 777'), ('A32X', 'Airbus 32X'), ('A33X', 'Airbus 33X'), ('MULTY', 'MULTY TYPE')], max_length=10, verbose_name='Тип ВС'),
        ),
    ]
