# Generated by Django 6.0.7 on 2026-08-16 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0008_alter_question_ac_type_alter_questiondraft_ac_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['theme__name', 'question'], 'permissions': [('can_publish', 'Can publish/unpublish questions'), ('can_restore', 'Can restore archived questions')], 'verbose_name': 'Вопрос', 'verbose_name_plural': 'Вопросы'},
        ),
        migrations.AlterModelOptions(
            name='questiondraft',
            options={'ordering': ['-updated_at'], 'permissions': [('can_publish', 'Can publish')], 'verbose_name': 'Черновик вопроса', 'verbose_name_plural': 'Черновики вопросов'},
        ),
        migrations.AlterModelOptions(
            name='questionparaphrase',
            options={'ordering': ['-created_at'], 'permissions': [('can_publish', 'Can publish/unpublish paraphrase')], 'verbose_name': 'Перефразированный вопрос', 'verbose_name_plural': 'Перефразированные вопросы'},
        ),
    ]
