# Generated by Django 6.0.7 on 2026-08-24 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0009_alter_question_options_alter_questiondraft_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='themes',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлена'),
        ),
    ]
