# Generated by Django 6.0.7 on 2026-08-16 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DescriptionPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True, verbose_name='Идентификатор раздела')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('content', models.TextField(blank=True, verbose_name='Содержание')),
            ],
            options={
                'verbose_name': 'Страница описания',
                'verbose_name_plural': 'Страницы описания',
                'ordering': ['id'],
            },
        ),
    ]
