# Generated by Django 6.0.7 on 2026-07-29 06:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('questions', '0002_alter_answer_options_remove_question_is_draft_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(choices=[('question', 'Активный вопрос'), ('draft', 'Черновик'), ('paraphrase', 'Перефразировка')], help_text='С каким вопросом связана запись истории (Черновик, основной вопрос, перефраз)', max_length=20, verbose_name='Тип сущности')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('logical_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='questions.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'История вопроса',
                'verbose_name_plural': 'Истории вопросов',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст комментария')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_comments', to=settings.AUTH_USER_MODEL)),
                ('history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='history.questionhistory')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('created', 'Создан'), ('updated_field', 'Изменение поля'), ('published', 'Публикация'), ('unpublished', 'Снятие с публикации'), ('archived', 'Архивирование'), ('restored', 'Восстановление из архива')], max_length=20)),
                ('field_name', models.CharField(blank=True, help_text='Для типа "updated_field"', max_length=100, null=True)),
                ('old_value', models.TextField(blank=True, null=True)),
                ('new_value', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='history.questionhistory')),
            ],
            options={
                'verbose_name': 'Действие',
                'verbose_name_plural': 'Действия',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='DraftView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now=True)),
                ('draft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='questions.questiondraft')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='draft_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Просмотр черновика',
                'verbose_name_plural': 'Просмотры черновиков',
                'indexes': [models.Index(fields=['user', 'viewed_at'], name='history_dra_user_id_eda192_idx')],
                'unique_together': {('user', 'draft')},
            },
        ),
    ]
