# Generated by Django 6.0.7 on 2026-08-04 09:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='questionhistory',
            name='user_name',
            field=models.CharField(blank=True, help_text='Сохраняется на момент создания записи. Используется, если пользователь удалён.', max_length=150, verbose_name='Имя пользователя'),
        ),
        migrations.AlterField(
            model_name='questionhistory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата действия'),
        ),
        migrations.AlterField(
            model_name='questionhistory',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='question_history', to=settings.AUTH_USER_MODEL),
        ),
    ]
