# Generated by Django 6.0.7 on 2026-08-04 09:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0002_questionhistory_user_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='user_name',
            field=models.CharField(blank=True, help_text='Сохраняется на момент создания. Используется, если пользователь удалён.', max_length=150, verbose_name='Имя пользователя'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='question_comments', to=settings.AUTH_USER_MODEL),
        ),
    ]
