# Generated by Django 6.0.7 on 2026-08-04 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0003_comment_user_name_alter_comment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='action_type',
            field=models.CharField(choices=[('created', 'Создание вопроса'), ('updated_field', 'Изменение поля'), ('published', 'Публикация'), ('unpublished', 'Снятие с публикации'), ('archived', 'Архивирование'), ('restored', 'Восстановление из архива')], max_length=20),
        ),
    ]
