# Generated by Django 6.0.7 on 2026-08-07 16:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0004_alter_action_action_type'),
        ('questions', '0007_alter_answer_question'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='action_type',
            field=models.CharField(choices=[('created', 'Создан'), ('updated_field', 'Изменение поля'), ('published', 'Публикация'), ('unpublished', 'Снятие с публикации'), ('archived', 'Архивирование'), ('restored', 'Восстановление из архива'), ('deleted', 'Удалён')], max_length=20),
        ),
        migrations.CreateModel(
            name='TabView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tab_type', models.CharField(choices=[('question', 'Вопрос'), ('draft', 'Черновик'), ('paraphrase', 'Перефраз')], max_length=20, verbose_name='Тип вкладки')),
                ('viewed_at', models.DateTimeField(auto_now=True, verbose_name='Дата просмотра')),
                ('logical_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tab_views', to='questions.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tab_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Просмотр вкладки',
                'verbose_name_plural': 'Просмотры вкладок',
                'indexes': [models.Index(fields=['user', 'viewed_at'], name='history_tab_user_id_a15ec5_idx'), models.Index(fields=['logical_question', 'tab_type'], name='history_tab_logical_723338_idx')],
                'unique_together': {('user', 'logical_question', 'tab_type')},
            },
        ),
    ]
