# Generated by Django 6.0.7 on 2026-08-11 15:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0005_alter_action_action_type_tabview'),
        ('questions', '0008_alter_question_ac_type_alter_questiondraft_ac_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(blank=True, help_text='Сохраняется на случай удаления пользователя', max_length=150, verbose_name='Имя пользователя')),
                ('entity_type', models.CharField(choices=[('question', 'Вопрос'), ('theme', 'Тема'), ('user', 'Пользователь'), ('group', 'Группа')], max_length=20, verbose_name='Тип сущности')),
                ('entity_id', models.IntegerField(verbose_name='ID сущности')),
                ('entity_name', models.CharField(blank=True, max_length=500, verbose_name='Название сущности')),
                ('action_type', models.CharField(choices=[('created', 'Создание'), ('updated', 'Изменение'), ('deleted', 'Удаление'), ('published', 'Публикация'), ('unpublished', 'Снятие с публикации'), ('blocked', 'Блокировка'), ('unblocked', 'Разблокировка'), ('registered', 'Регистрация')], max_length=20, verbose_name='Действие')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата события')),
                ('theme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='questions.themes', verbose_name='Тема (для фильтрации по редакторам)')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to=settings.AUTH_USER_MODEL, verbose_name='Кто совершил')),
            ],
            options={
                'verbose_name': 'Запись активности',
                'verbose_name_plural': 'Журнал активности',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['entity_type', 'entity_id'], name='history_act_entity__12f46a_idx'), models.Index(fields=['theme', '-created_at'], name='history_act_theme_i_7b9ee5_idx'), models.Index(fields=['action_type'], name='history_act_action__dd2520_idx'), models.Index(fields=['created_at'], name='history_act_created_8e1995_idx')],
            },
        ),
    ]
