# Generated by Django 6.0.7 on 2026-08-11 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0006_activitylog'),
        ('questions', '0008_alter_question_ac_type_alter_questiondraft_ac_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabview',
            name='logical_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tab_views', to='questions.question'),
        ),
    ]
