# Generated by Django 6.0.7 on 2026-08-24 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0007_alter_tabview_logical_question'),
        ('questions', '0009_alter_question_options_alter_questiondraft_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tabview',
            name='theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tab_views', to='questions.themes', verbose_name='Тема'),
        ),
    ]
