# Generated by Django 6.0.7 on 2026-08-24 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0008_tabview_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabview',
            name='tab_type',
            field=models.CharField(choices=[('question', 'Вопрос'), ('draft', 'Черновик'), ('paraphrase', 'Перефраз'), ('theme', 'Тема')], max_length=20, verbose_name='Тип вкладки'),
        ),
    ]
