# Generated by Django 6.0.7 on 2026-09-02 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0009_alter_tabview_tab_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabview',
            name='tab_type',
            field=models.CharField(choices=[('question', 'Вопрос'), ('draft', 'Черновик'), ('paraphrase', 'Перефраз'), ('theme', 'Тема')], max_length=20),
        ),
        migrations.AlterField(
            model_name='tabview',
            name='viewed_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
